name = "daily-recap-workflow"
main = "src/index.ts"
compatibility_date = "2024-12-05"

[observability]
enabled = true

[[workflows]]
# name of your workflow
name = "daily-recap-workflow"
# binding name env.MYWORKFLOW
binding = "DAILY_RECAP_WORKFLOW"
# this is the class that extends the Workflow class in src/index.ts
class_name = "DailyRecapWorkflow"

[[r2_buckets]]
bucket_name = ""
preview_bucket_name = "-dev"
binding = "IMAGES_BUCKET"

[[d1_databases]]
binding = "DB"
database_name = ""
database_id = ""

[ai]
binding = "AI"

[triggers]
crons = [ "0 6 * * *" ]

[dev]
port = 8788

[[workflows]]
name = "get-users-for-recap-workflow"
binding = "GET_USERS_WORKFLOW"
class_name = "GetUsersForRecapWorkflow"
